### PR TITLE
added run config for mkdocs so can debug in vscode

### PR DESCRIPTION
**Pull request by alexvoss**
I am having some troubles compiling the examples, so added a run configuration for debugging the `mkdocs` process. 

Should work for everyone and I can add a small tutorial or something? LMK where you would like that:

- main documentation under `customization/#environment-setup`?
- as a tutorial here in examples?
- on youtube somewhere? (got Screenflow, so recording something should be poss.)

### CODE REVIEW

**Review by squidfunk — APPROVED** [review]

**Comment by squidfunk** [comment]
Thanks! We can add something to the main README, but remember that it only applies to VSCode and other users might be using other editors. I suspect that setting `PYTHONPATH` was the main problem, right? That should definitely go into the README.

**Comment by alexvoss** [comment]
Figuring out that PYTHONPATH was needed was one thing but that did not take very long. The reason I had to turn on the debugger was that `examples/__init__.py` in line 52 assumes that there is a `features` attribute on the Theme, which I did not have on a newly created example. Might be worth adding a conditional?

**Comment by alexvoss** [comment]
Running into another problem just now:  

```
INFO    -  [20:35:45] Detected file changes
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/Users/avoss/src/mkdocs-material/examples/venv/lib/python3.11/site-packages/watchdog/observers/api.py", line 204, in run
    self.dispatch_events(self.event_queue)
  File "/Users/avoss/src/mkdocs-material/examples/venv/lib/python3.11/site-packages/watchdog/observers/api.py", line 380, in dispatch_events
    handler.dispatch(event)
  File "/Users/avoss/src/mkdocs-material/examples/venv/lib/python3.11/site-packages/watchdog/events.py", line 275, in dispatch
    self.on_any_event(event)
  File "/Users/avoss/src/mkdocs-material/examples/venv/lib/python3.11/site-packages/material/plugins/projects/plugin.py", line 314, in resolve
    del self.pool_jobs[slug]
        ~~~~~~~~~~~~~~^^^^^^
KeyError: '.statusbadge'
INFO    -  Building documentation...
```

So, `mkdocs serve` keeps running but the example I am working on does not get re-built. Posting this in case you can see easily what the issue is, @squidfunk

**Comment by squidfunk** [comment]
Did you create the example while you were running `mkdocs serve`? If you can explain exactly what you did to trigger the error, I'm happy to look into it. You know how it goes – without knowing how to observe, no chance of fixing 😅

**Pull request merged**
